In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(a))
print(a.shape)
print(type(b))
print(b.shape)
print(type(c))
print(c.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(3, 3)


In [ ]:
# Creates a 2X2 zeros array
c=np.zeros((2,2))
# Creates a 2X4 ones array
d=np.ones((2,4))
# Creates a 3X2 array filled with random values
e = np.random.randint((3,2))
# Creates a range of elements till 7
f = np.arange(7)

print(c)
print(d)
print(e)
print(f)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1]
[0 1 2 3 4 5 6]


In [ ]:
print(np.sum(a))
print(np.mean(b))
print(np.min(c))
print(np.max(d))

6
3.5
0.0
1.0


In [3]:
np.random.seed(42)  # For reproducibility
student_marks = np.random.randint(0, 101, size=50)  # Assuming 50 students


passing_marks = student_marks >= 30
num_students_passed = np.sum(passing_marks)
print("Number of students passed:", num_students_passed)

failed_marks = student_marks[student_marks < 30]
print("Failed marks:",failed_marks)

Number of students passed: 36
Failed marks: [14 20 23  2 21  1 29  1 20 21 14  2  6 20]


In [4]:
random_array = np.random.randint(1, 51, size=(5, 5))  # Creating a 5x5 array, adjust size as needed

print("Random 2D array:")
print(random_array)

Random 2D array:
[[39 18  4 25 14]
 [50  9 26  2 20]
 [28 47  7 44  8]
 [47 35 14 17 36]
 [50 40  4  2  6]]


In [5]:
odd_numbers = np.arange(-29, 11, 2)
print("Array of odd numbers between -30 and 10:")
print(odd_numbers)

Array of odd numbers between -30 and 10:
[-29 -27 -25 -23 -21 -19 -17 -15 -13 -11  -9  -7  -5  -3  -1   1   3   5
   7   9]
